# Generated by Django 6.0.2 on 2026-02-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
